service: wan-bus-api
frameworkVersion: '2'
plugins:
  - serverless-domain-manager

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  region: ap-southeast-2


custom:
  customDomain:
    domainName: bus.dh.wtf
    stage: ${self:provider.stage}
    basePath: api
    certificateName: '*.dh.wtf'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    # apiType: rest
    # autoDomain: false


functions:
  app-api:
    handler: handler.handler
    timeout: 10 #secs
    memorySize: 128 #mb
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
